### ISSUE TITLE
What is this repo used for? Can you explain in detail?

### ISSUE THREAD

**Issue by wxjiao** [cuhk-bme-group-aaron/CNC-Appointment#2]

**Comment by CUHKBME-GroupA** [comment]
It's just a try for online equipment appointment, but now we have a more intuitive solution, please try google calendar😁
Here is the link
https://calendar.google.com/calendar/b/0/r?cid=czBtcW5xMzgxbzlvZWRjMzA5ZXVzdDc3NW9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
